### ISSUE TITLE
Autostart.sh homebrew entry when should be ports

### ISSUE THREAD

**Issue by Rocky5** [AmberELEC/AmberELEC#913]
https://github.com/AmberELEC/AmberELEC/blob/1a99ba28ce768ae3a467cef0d1889703e8b75d25/packages/amberelec/sources/autostart.sh

The issue is it keeps copying the usr/config/ports/ to storage/roms/homebrew

The menu system doesn’t look for homebrew, so it’s just left there taking up 50MB of space. 

Option to remove this completely or at the very least copy to the right folder.

**Comment by dhwz** [comment]
There is absolutely nothing wrong here, the two games in homebrew are hidden (because they are just for internal use) in gamelist.xml thats why they are not visible, if you want them be visible you've to remove the hidden flag from gamelist.xml.

And they don't belong in ports, ports is reserved for Portmaster usage.

**Comment by Rocky5** [comment]
Ah ok my mistake, I didn’t realise I had to remove the hidden flags.
